# Generated by Django 5.2.11 on 2026-03-01 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_alter_course_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Dars nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib')),
                ('duration', models.PositiveIntegerField(blank=True, default=30, verbose_name='Davomiyligi (minut)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Resurs nomi')),
                ('type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('pptx', 'PPTX'), ('docx', 'DOCX'), ('link', 'Havola')], max_length=20, verbose_name='Turi')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_resources/', verbose_name='Fayl')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL (Video yoki havola)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Dars Resurs',
                'verbose_name_plural': 'Dars Resurslar',
                'ordering': ['lesson', 'order'],
            },
        ),
    ]
