# Generated by Django 5.2.1 on 2026-03-04 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_lessonresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Olingan ball')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Maksimal ball')),
                ('answers', models.JSONField(default=list, verbose_name='Javoblar')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (sekundlarda)')),
                ('correct_answers', models.PositiveIntegerField(verbose_name="To'g'ri javoblar soni")),
                ('total_questions', models.PositiveIntegerField(verbose_name='Umumiy savol soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
