# Generated by Django 5.2.1 on 2026-03-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresource',
            name='audio_url',
            field=models.URLField(blank=True, default='', verbose_name='Audio URL'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Xato xabari'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='processing_status',
            field=models.CharField(choices=[('idle', 'Kutilmoqda'), ('extracting', 'Matn ajratilmoqda'), ('scripting', 'Skript yaratilmoqda'), ('audio', 'Ovoz yaratilmoqda'), ('video', 'Video yaratilmoqda'), ('quiz', 'Test yaratilmoqda'), ('ready', 'Tayyor'), ('failed', 'Xato')], default='idle', max_length=20, verbose_name='Qayta ishlash holati'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='script',
            field=models.TextField(blank=True, default='', verbose_name='Video skript'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='transcript',
            field=models.TextField(blank=True, default='', verbose_name='Transkript'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='ai_feedback',
            field=models.TextField(blank=True, default='', verbose_name='AI tahlili'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, verbose_name='Tavsiyalar'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='weak_topics',
            field=models.JSONField(blank=True, default=list, verbose_name='Zaif mavzular'),
        ),
    ]
