# Generated by Django 4.2.7 on 2026-04-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lessonresource_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.lessonresource', verbose_name='Dars Resurs'),
        ),
    ]
