# Generated by Django 4.2.7 on 2026-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_test_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresource',
            name='has_quiz',
            field=models.BooleanField(default=False, verbose_name='Test mavjud'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='video_url',
            field=models.URLField(blank=True, default='', verbose_name='Video URL'),
        ),
    ]
