# Generated by Django 5.2.12 on 2026-04-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lessonresource_has_quiz_lessonresource_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image_position',
            field=models.CharField(blank=True, choices=[('top', 'Tepada'), ('right', "O'ngda"), ('bottom', 'Pastda'), ('left', 'Chapda')], default='top', max_length=10),
        ),
    ]
