# Generated by Django 5.2.12 on 2026-04-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_question_earned_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='earned_points',
            field=models.PositiveIntegerField(default=0, verbose_name="Yig'ilgan ball"),
        ),
    ]
