# Generated by Django 5.2.1 on 2026-03-08 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseenrollment'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.IntegerField(default=0, verbose_name="Ko'rilgan sekundlar")),
                ('total_seconds', models.IntegerField(default=0, verbose_name='Jami sekundlar')),
                ('completed', models.BooleanField(default=False, verbose_name='Tugallangan')),
                ('last_watched', models.DateTimeField(auto_now=True, verbose_name="Oxirgi ko'rilgan vaqti")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('lesson_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.lessonresource', verbose_name='Dars Resurs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Video progressi',
                'verbose_name_plural': 'Video progresslari',
                'unique_together': {('student', 'lesson_resource')},
            },
        ),
    ]
